### ISSUE TITLE
Merged data

### ISSUE THREAD

**Issue by xiaoguang1988** [metaOmic/metaOmics#27]
![screen shot 2016-08-31 at 2 57 04 pm](https://cloud.githubusercontent.com/assets/6474826/18142371/405e8ea4-6f8b-11e6-9a3d-f05176a0b7a2.png)
After data are merged, data type is continuous.

**Comment by schwannden** [comment]
Yes we have discussed this. The thing is, since you can merge microarray and RNA sequence FPKM data, what should we call the data type of a merged study of different type? I have discussed with @matianzhou , and at the moment, we don't see the need to indicate it is a mixed type, so for a multiple study, one only need continuous or discrete type.
